### ISSUE TITLE
Implement the Counting Sort algorithm

### ISSUE THREAD

**Issue by sentenza** [sentenza/hacktoberfest-scala-algorithms#14]
https://github.com/sentenza/hacktoberfest-scala-algorithms/blob/1e541a09eb9d7eb0dbec7feebb3d1d13d7f4c06a/src/main/scala/io/github/sentenza/hacktoberfest18/sort/CommonSortings.scala#L33

>  Counting sort is an algorithm for sorting a collection of objects according to keys that are small integers; that is, it is an integer sorting algorithm. It operates by counting the number of objects that have each distinct key value, and using arithmetic on those counts to determine the positions of each key value in the output sequence.

### Contributing Guidelines
- Add the missing implementation of the [Counting Sort](https://en.wikipedia.org/wiki/Counting_sort)
- Add a test case in the spec that targets the `CommonSorting` object
- Don't be afraid to submit a new PR
- Have fun!

**Comment by saj1th** [comment]
could take a look

**Comment by saj1th** [comment]
any thoughts on adding .scalafmt.conf ?
