### ISSUE TITLE
Implement the Radix Sort algorithm

### ISSUE THREAD

**Issue by sentenza** [sentenza/hacktoberfest-scala-algorithms#15]
https://github.com/sentenza/hacktoberfest-scala-algorithms/blob/1e541a09eb9d7eb0dbec7feebb3d1d13d7f4c06a/src/main/scala/io/github/sentenza/hacktoberfest18/sort/CommonSortings.scala#L34

> Radix sort is a non-comparative integer sorting algorithm that sorts data with integer keys by grouping keys by the individual digits which share the same significant position and value. A positional notation is required, but because integers can represent strings of characters (e.g., names or dates) and specially formatted floating point numbers, radix sort is not limited to integers.

### Contributing Guidelines
- Add the missing implementation of the [Radix Sort](https://en.wikipedia.org/wiki/Radix_sort)
- Add a test case in the spec that targets the `CommonSorting` object
- Don't be afraid to submit a new PR
- Have fun!

**Comment by spartan-vishan** [comment]
yikes, I got busy with school and looks like my pull request was closed. I just committed code without checking that. How do I proceed? Hope I didn't mess anything up
