### ISSUE TITLE
Implement the Bucket Sort algorithm

### ISSUE THREAD

**Issue by sentenza** [sentenza/hacktoberfest-scala-algorithms#16]
https://github.com/sentenza/hacktoberfest-scala-algorithms/blob/1e541a09eb9d7eb0dbec7feebb3d1d13d7f4c06a/src/main/scala/io/github/sentenza/hacktoberfest18/sort/CommonSortings.scala#L35

> Bucket sort, or bin sort, is a sorting algorithm that works by distributing the elements of an array into a number of buckets. Each bucket is then sorted individually, either using a different sorting algorithm, or by recursively applying the bucket sorting algorithm. It is a **distribution sort**, a generalization of pigeonhole sort, and is a cousin of radix sort in the most-to-least significant digit flavor.

### Contributing Guidelines
- Add the missing implementation of the [Bucket Sort](https://en.wikipedia.org/wiki/Bucket_sortt)
- Add a test case in the spec that targets the `CommonSorting` object
- Don't be afraid to submit a new PR
- Have fun!

**Comment by Xoeseko** [comment]
I wanted to assign this issue to myself as suggested but I think only collaborators can. Can you please assign it to me ? @sentenza

**Comment by sentenza** [comment]
> I wanted to assign this issue to myself as suggested but I think only collaborators can. Can you please assign it to me ? @sentenza

No worries, I will accept only your PR for this issue. ;)

**Comment by Xoeseko** [comment]
Thanks for that, whenever you have time have a look at my implementation #18

**Comment by ivanopagano** [comment]
Isn't this issue closed by #18 ? @sentenza
