### ISSUE TITLE
Add or improve any sorting algorhitms

### ISSUE THREAD

**Issue by sentenza** [sentenza/hacktoberfest-scala-algorithms#2]
**Contributing Guidelines**

* Each new contribution should be added to the `/sort` folder

https://github.com/sentenza/hacktoberfest-scala-algorithms/blob/456108fbc8e36072099debb2704f8b37002e8795/src/main/scala/io/github/sentenza/hacktoberfest18/sort/CommonSortings.scala#L28

* It is your choice to include only a function or an entire trait/object/class to describe the algorithm you worked on .
* If the folder/file does not exist, create a new one.
* Don't be afraid to make a Pull Request!

**Comment by Lacaranian** [comment]
I might take a crack at this
