### ISSUE TITLE
Writing the main loop in FP style

### ISSUE THREAD

**Issue by sentenza** [sentenza/hacktoberfest-scala-algorithms#23]
What we should aim for is to change the way we fetch the input from the console and then manage the loop that keeps showing the prompt. 

We need:
- out of the loop - print the LOGO and disclaimer
- on request and at the very beginning: show the list of types (searching, sorting) 
- a `showPrompt(): Unit` method to print out  a prompt to select the type of algorithm to execute
- after selecting the type, we should give the user the ability to pick up one of the implemented algorithms
- print out the results, and the loop begins again
- the loop must be annotated with `@tailrec`

```scala
/**
  * A fairly standard "print this out" / "read this in" Scala recursive function
  */
@tailrec
def mainLoop(appState: AppState) {
    // a) prompt the user for input
    // b) get the user's input
    // c) execute the chosen algorithm / show a menu
    // d) write the output
    // e) if the user didn't type 'q' or 'quit' loop again
    mainLoop(newAppState)
}
```

**Comment by ivanopagano** [comment]
I was always a bit confused as to what should be shown when selecting an algorithm?

what should the following point do?

> - print out the results, and the loop begins again

**Comment by sentenza** [comment]
> I was always a bit confused as to what should be shown when selecting an algorithm?
> what should the following point do?
> 
> > * print out the results, and the loop begins again

My first idea was essentially:

1. select the kind of algorithm (search, sort, whatever)
2. show the list of available functions
3. print out the original collection and the sorted one
4. show the results, taking advantage of @Astrac's [box-tables](https://github.com/Astrac/box-tables)

**Comment by ivanopagano** [comment]
ahaha, I like the last point!

Ok, thanks @sentenza
